//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BMS_DBEntities : DbContext
    {
        public BMS_DBEntities()
            : base("name=BMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeInfo> EmployeeInfoes { get; set; }
        public virtual DbSet<OperateRecordInfo> OperateRecordInfoes { get; set; }
        public virtual DbSet<RateInfo> RateInfoes { get; set; }
        public virtual DbSet<UserAccountInfo> UserAccountInfoes { get; set; }
        public virtual DbSet<BusinessLoanInfo> BusinessLoanInfoes { get; set; }
        public virtual DbSet<StudentLoanInfo> StudentLoanInfoes { get; set; }
        public virtual DbSet<PersonalLoanInfo> PersonalLoanInfoes { get; set; }
    }
}
