//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessLoanInfo
    {
        public int BlId { get; set; }
        public string BlAccountNumber { get; set; }
        public string BlCompany { get; set; }
        public string BlCompanyLoaction { get; set; }
        public string BlCompanyAsset { get; set; }
    
        public virtual UserAccountInfo UserAccountInfo { get; set; }
    }
}
