//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public string EId { get; set; }
        public string EPassword { get; set; }
        public string EName { get; set; }
        public string ESex { get; set; }
        public string EIdCardNumber { get; set; }
        public string EPhone { get; set; }
        public Nullable<decimal> ESalary { get; set; }
        public string EDepartment { get; set; }
    }
}
