//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLoanInfo
    {
        public int SlId { get; set; }
        public string SlAccountNumber { get; set; }
        public string SlSchool { get; set; }
        public string SlInstitute { get; set; }
        public string SlProfession { get; set; }
    
        public virtual UserAccountInfo UserAccountInfo { get; set; }
    }
}
