//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountInfo
    {
        public UserAccountInfo()
        {
            this.OperateRecordInfoes = new HashSet<OperateRecordInfo>();
            this.BusinessLoanInfoes = new HashSet<BusinessLoanInfo>();
            this.StudentLoanInfoes = new HashSet<StudentLoanInfo>();
            this.PersonalLoanInfoes = new HashSet<PersonalLoanInfo>();
        }
    
        public string UAccountNumber { get; set; }
        public string UName { get; set; }
        public string USex { get; set; }
        public string UIdCardNumber { get; set; }
        public string UPhone { get; set; }
        public Nullable<System.DateTime> UAccountDate { get; set; }
        public string UAccountPassword { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string DepositId { get; set; }
        public string LoanType { get; set; }
        public string Statement { get; set; }
    
        public virtual ICollection<OperateRecordInfo> OperateRecordInfoes { get; set; }
        public virtual RateInfo RateInfo { get; set; }
        public virtual ICollection<BusinessLoanInfo> BusinessLoanInfoes { get; set; }
        public virtual ICollection<StudentLoanInfo> StudentLoanInfoes { get; set; }
        public virtual ICollection<PersonalLoanInfo> PersonalLoanInfoes { get; set; }
    }
}
